---

tuxedo_service_group: tuxedo
tuxedo_service_group_id: 1010
tuxedo_service_user_id_minimum: 1010
tuxedo_service_user_id_increment: 10
tuxedo_service_users:
  - name: ceu
    uid:  "{{ tuxedo_service_user_id_minimum + (0 * tuxedo_service_user_id_increment) | int }}"
  - name: chd
    uid:  "{{ tuxedo_service_user_id_minimum + (1 * tuxedo_service_user_id_increment) | int }}"
  - name: chic
    uid: "{{ tuxedo_service_user_id_minimum + (2 * tuxedo_service_user_id_increment) | int }}"
  - name: xml
    uid: "{{ tuxedo_service_user_id_minimum + (3 * tuxedo_service_user_id_increment) | int }}"

# TODO second phase: Informix install and additional users

# TODO check live equivalents
# global_resource_limits:
#   hard:
#     nofile: 8192
#     nproc: 4096
#     stack: unlimited
#     msgqueue: 819200
#   soft:
#     nofile: 8192
#     nproc: 4096
#     stack: 10240
#     msgqueue: 819200

# oracle_database_version: "10.2.0"
# oracle_database_install_directory: "/opt/oracle/{{ oracle_database_version }}"

# If locale is ever changed from 'C', a symlink with the same name should be created
# in $TUXDIR/locale pointing at $TUXDIR/locale/C for message strings to resolve correctly
system_locale: C

tuxedo_version: "8.1"
tuxedo_install_directory: "/opt/tuxedo/{{ tuxedo_version }}"

deployment_dir: deployment
envfile_name: envfile
