---

tuxedo_service_group: tuxedo
tuxedo_service_group_id: 1010
tuxedo_service_user_id_minimum: 1010
tuxedo_service_user_id_increment: 10
tuxedo_service_users:
  - name: ceu
    uid:  "{{ tuxedo_service_user_id_minimum + (0 * tuxedo_service_user_id_increment) | int }}"
  - name: ois
    uid:  "{{ tuxedo_service_user_id_minimum + (1 * tuxedo_service_user_id_increment) | int }}"
  - name: publ
    uid: "{{ tuxedo_service_user_id_minimum + (2 * tuxedo_service_user_id_increment) | int }}"
  - name: xml
    uid: "{{ tuxedo_service_user_id_minimum + (3 * tuxedo_service_user_id_increment) | int }}"
  - name: wck
    uid: "{{ tuxedo_service_user_id_minimum + (4 * tuxedo_service_user_id_increment) | int }}"

# If locale is ever changed from 'C', a symlink with the same name should be created
# in $TUXDIR/locale pointing at $TUXDIR/locale/C for message strings to resolve correctly
system_locale: C

tuxedo_version: "8.1"
tuxedo_install_directory: "/opt/tuxedo/{{ tuxedo_version }}"

informix_sdk_version: "410UC12"
informix_install_directory: "/opt/informix-client-sdk/{{ informix_sdk_version }}"

deployment_dir: deployment
envfile_name: envfile
